from django.shortcuts import render
from InformTable.models import PersonalInformation, EssentialInformation
# Create your views here.


def postdiagnose(request):
    info = PersonalInformation()
    info2 = EssentialInformation()
    if request.POST:
        info.id = request.POST.get("id")
        info.name = request.POST.get("name")
        info.age = request.POST.get("age")
        info.sex = request.POST.get("sex")
        info.nation = request.POST.get("nation")
        info.marriage = request.POST.get("marriage")
        info.occupation = request.POST.get("occupation")
        info.birthplace = request.POST.get("birthplace")
        info.address = request.POST.get("address")
        info.medicalhistory_reporter = request.POST.get("medicalhistory_reporter")
        info.admission_date = request.POST.get("admission_date")
        info.medicalhistory_recordtime = request.POST.get("medicalhistory_recordtime")
        info.save()

        info2.id = request.POST.get("id")
        info2.main_suit = request.POST.get("main_suit")
        info2.medicalhistory_present = request.POST.get("medicalhistory_present")
        info2.tuberculosis_history = request.POST.get("tuberculosis_history")
        info2.hepatitis_history = request.POST.get("hepatitis_history")
        info2.other_infectious_diseases_history = request.POST.get("other_infectious_diseases_history")
        info2.hypertension_history = request.POST.get("hypertension_history")
        info2.diabetes_mellitus_history = request.POST.get("diabetes_mellitus_history")
        info2.chronic_disease_history = request.POST.get("chronic_disease_history")
        info2.heart_disease_history = request.POST.get("heart_disease_history")
        info2.vaccination_allergy_history = request.POST.get("vaccination_allergy_history")
        info2.surgery_history = request.POST.get("surgery_history")
        info2.past_history_remarks = request.POST.get("past_history_remarks")
        info2.birthplace = request.POST.get("birthplace")
        info2.smoking_hobbies = request.POST.get("smoking_hobbies")
        info2.drinking_hobbies = request.POST.get("drinking_hobbies")
        info2.epidemic_water_contact_history = request.POST.get("epidemic_water_contact_history")
        info2.personal_history_remark = request.POST.get("personal_history_remark")
        info2.marriage = request.POST.get("marriage")
        info2.marital_reproductive_history_remark = request.POST.get("marital_reproductive_history_remark")
        info2.menopause = request.POST.get("menopause")
        info2.menstrual_history_remark = request.POST.get("menstrual_history_remark")
        info2.diabetes_mellitus_family_history = request.POST.get("diabetes_mellitus_family_history")
        info2.coronary_heart_disease_family_history = request.POST.get("coronary_heart_disease_family_history")
        info2.stroke_family_history = request.POST.get("stroke_family_history")
        info2.tumors_family_history = request.POST.get("tumors_family_history")
        info2.hypertension_family_history = request.POST.get("hypertension_family_history")
        info2.family_history_remark = request.POST.get("family_history_remark")
        info2.save()
    return render(request, "DetailInform.html")