# Generated by Django 2.2.5 on 2019-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamine',
            name='left_lens',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyeexamine',
            name='left_vitreum',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyeexamine',
            name='right_lens',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyeexamine',
            name='right_vitreum',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
