# Generated by Django 2.2.5 on 2019-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0002_auto_20190922_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreports',
            name='diaResult',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticreports',
            name='reportTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='main_suit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='medicalhistory_present',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_anteriorchamber_central',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_anteriorchamber_surrounded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_fundusoculi_detailinform',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_intraocularpressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_lens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_pupil_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_vision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_vitreum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_anteriorchamber_central',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_anteriorchamber_surrounded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_fundusoculi_detailinform',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_intraocularpressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_lens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_pupil_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_vision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_vitreum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='medicalhistory_recordtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
