# Generated by Django 2.2.5 on 2019-09-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0004_auto_20190922_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_intraocularpressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='left_vision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_intraocularpressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexamine',
            name='right_vision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
