# Generated by Django 2.2.5 on 2019-10-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0007_auto_20190923_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=60)),
                ('pvillage', models.CharField(max_length=60)),
                ('presult', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('v_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=60)),
                ('vdetailaddress', models.CharField(max_length=60)),
                ('vleadingname', models.CharField(max_length=60)),
                ('vleadingtel', models.CharField(max_length=30)),
                ('vorderedtime', models.DateField()),
                ('vmessage', models.TextField()),
            ],
        ),
    ]
