# Generated by Django 2.2.5 on 2019-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0008_patient_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChestExamine',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('chest_contour', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('respiratory_sounds', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('dryrale', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('wetrale', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('heart_rate', models.IntegerField()),
                ('arrhythmia', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExamine',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('pulse', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('routine_info', models.TextField()),
                ('yellow_dye', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('lymphgland', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('neck_info', models.TextField()),
                ('face_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StomachExamine',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('abdomen_soft', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('abdomen_tenderness', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('abdomen_rebound_pain', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('subcostal_liver', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('subcostal_spleen', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('limb_joint', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('limb_movement', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('physiological_reflex', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('pathological_reflex', models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
