# Generated by Django 2.2.5 on 2019-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialinformation',
            name='family_history_remark',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='marital_reproductive_history_remark',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='past_history_remarks',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='personal_history_remark',
            field=models.TextField(default='无'),
        ),
    ]
