# Generated by Django 2.2.5 on 2019-09-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0002_auto_20190911_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialinformation',
            name='family_history_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='marital_reproductive_history_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='past_history_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='personal_history_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
