# Generated by Django 2.2.5 on 2019-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0003_auto_20190911_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialinformation',
            name='marriage',
            field=models.CharField(choices=[('已婚', 'true'), ('未婚', 'false')], max_length=2),
        ),
    ]
