# Generated by Django 2.2.5 on 2019-09-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0004_auto_20190915_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialinformation',
            name='marriage',
            field=models.CharField(choices=[('已婚', '已婚'), ('未婚', '未婚')], max_length=2),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='marriage',
            field=models.CharField(choices=[('已婚', '已婚'), ('未婚', '未婚')], max_length=2),
        ),
    ]
