# Generated by Django 2.2.5 on 2019-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformTable', '0006_auto_20190915_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialinformation',
            name='chronic_disease_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='coronary_heart_disease_family_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='diabetes_mellitus_family_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='diabetes_mellitus_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='drinking_hobbies',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='epidemic_water_contact_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='heart_disease_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='hepatitis_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='hypertension_family_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='hypertension_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='marriage_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='menopause',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='menstrual_history_remark',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='other_infectious_diseases_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='smoking_hobbies',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='stroke_family_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='surgery_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='tuberculosis_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='tumors_family_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
        migrations.AlterField(
            model_name='essentialinformation',
            name='vaccination_allergy_history',
            field=models.CharField(choices=[('有', 'yes'), ('无', 'no')], max_length=1),
        ),
    ]
